### ISSUE TITLE
new dependency libxml2?

### ISSUE THREAD

**Issue by itiligent** [yu210148/gvm_install#86]
Hi,

I've been tweaking the script for a range of distributed deployments on raspi, and have been testing on (official) ubuntu 20.04 for raspi and raspian bullseye.  Also testing with GVM 21.4.5

I suspect there is something not right when building the ospd-openvas lxml component. 

On Raspian and Ubuntu there are always a few errors being logged with python setups ie
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/opt/gvm/lib/python3.9/site-packages/ospd/main.py", line 83, in exit_cleanup
    server.close()
  File "/opt/gvm/lib/python3.9/site-packages/ospd/server.py", line 231, in close
    super().close()
  AttributeError: 'NoneType' object has no attribute 'shutdown' etc

Installing on raspi Ubuntu 20.04 I get more verbose errors relating to missing dependencies of  libxml2 (this is not included in the script). 
I suspect the same issues have been occurring when installing on Ubuntu 20.04 x64 as well.  say this becuase after adding libxml2 to the script, The installer (for the first time even after much play with this script) properly took its time to build lxml (setup.py) .. I'll test raspian another day but I exepect Raspian be the same.

**Comment by yu210148** [comment]
Hi again, I could add it. That shouldn't be a problem. Is it something that
could be added to one of the apt get commands? I'm not in front of my
computer right now.

Kev.

**Comment by yu210148** [comment]
It looks like libxml2-dev get's installed on line 117. I'll add in libxml2
there as well but it looks like it got pulled in somewhere along the way on
my instance running on 20.04.

kev.
